// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tapir.Models;

namespace Tapir.Migrations
{
    [DbContext(typeof(TapirContext))]
    [Migration("20181020174636_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tapir.Models.Address", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<int?>("CompanyID");

                    b.Property<string>("Country")
                        .HasMaxLength(50);

                    b.Property<string>("Street1")
                        .HasMaxLength(100);

                    b.Property<string>("Street2")
                        .HasMaxLength(100);

                    b.Property<string>("Zip")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Tapir.Models.BusinessSector", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("BusinessSectors");
                });

            modelBuilder.Entity("Tapir.Models.Company", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("InsuranceNumber")
                        .HasMaxLength(30);

                    b.Property<int?>("SectorID");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.HasIndex("SectorID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Tapir.Models.Employment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID");

                    b.Property<int>("PersonID");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("PersonID");

                    b.ToTable("Employments");
                });

            modelBuilder.Entity("Tapir.Models.Person", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressID")
                        .IsRequired();

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CityOfRegularEmployment")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("IsOwner");

                    b.Property<string>("Language")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double?>("OwnershipSelf");

                    b.Property<double?>("OwnershipWithFamily");

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("PlaceOfRegularEmployment")
                        .HasMaxLength(100);

                    b.Property<string>("PositionInCompany")
                        .HasMaxLength(100);

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("RegularEmploymentAddressID");

                    b.Property<string>("SSN");

                    b.Property<double?>("VotesSelf");

                    b.Property<double?>("VotesWithFamily");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("RegularEmploymentAddressID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Tapir.Models.Address", b =>
                {
                    b.HasOne("Tapir.Models.Company")
                        .WithMany("Addresses")
                        .HasForeignKey("CompanyID");
                });

            modelBuilder.Entity("Tapir.Models.Company", b =>
                {
                    b.HasOne("Tapir.Models.BusinessSector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID");
                });

            modelBuilder.Entity("Tapir.Models.Employment", b =>
                {
                    b.HasOne("Tapir.Models.Company", "Company")
                        .WithMany("Employments")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tapir.Models.Person", "Person")
                        .WithMany("Employments")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tapir.Models.Person", b =>
                {
                    b.HasOne("Tapir.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tapir.Models.Address", "RegularEmploymentAddress")
                        .WithMany()
                        .HasForeignKey("RegularEmploymentAddressID");
                });
#pragma warning restore 612, 618
        }
    }
}
